services:
  runner: 
    image: ikanpaus/self-runner:v1
    restart: always
    environment:
      - REPO: <owner/repo>
      - TOKEN: <token>
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          cpus: '0.75'
          memory: 1250M
        reservations:
          cpus: '0.25'
          memory: 128M
  
